[package]
name = "popcap-pak-wasm"
version = "0.0.0"
edition = "2024"
license = "MIT or Apache-2.0"

[lib]
crate-type = [ "cdylib" ]

[dependencies]
js-sys = "0.3.83"
popcap-pak = { path = "../popcap-pak" }
wasm-bindgen = "0.2.106"
